---

- name: Configure new VM
  hosts: "{{ target }}"
  gather_facts: false
  tasks:
    - name: Basline the new VM
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ hostvars[inventory_hostname].ansible_roles }}"
